# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.24.0
_src_path: pycliche
author_email: alberto.moronh@gmail.com
author_name: Alberto Morón Hernández
is_github_project: true
min_python_version: '3.14'
project_name: digitalocean_deployment_orchestrator
